version: "3"

services:
  zookeeper-west:
    image: confluentinc/cp-zookeeper:7.1.1-1-ubi8
    hostname: zookeeper-west
    container_name: zookeeper-west
    networks:
      - n1
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_SERVERS: zookeeper-west:2888:3888

  broker-west:
    image: confluentinc/cp-server:7.1.1-1-ubi8
    hostname: broker-west
    container_name: broker-west
    networks:
      - n1
    ports:
      - "19092:19092"
      - "18092:18092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "west"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-west:9092,LISTENER_DOCKER_EXTERNAL://broker-west:19092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-west:12181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-west:9092
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: "true"
      KAFKA_JMX_PORT: 18092
    depends_on:
      - zookeeper-west

  zookeeper-east:
    image: confluentinc/cp-zookeeper:7.1.1-1-ubi8
    hostname: zookeeper-east
    container_name: zookeeper-east
    networks:
      - n1
    ports:
      - "22182:22182"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22182
      ZOOKEEPER_SERVERS: zookeeper-east:2888:3888

  broker-east:
    image: confluentinc/cp-server:7.1.1-1-ubi8
    hostname: broker-east
    container_name: broker-east
    networks:
      - n1
    ports:
      - "29092:29092"
      - "28092:28092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "east"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-east:9092,LISTENER_DOCKER_EXTERNAL://broker-east:29092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-east:22182"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-east:9092
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: "true"
      KAFKA_JMX_PORT: 28092
    depends_on:
      - zookeeper-east

networks:
  n1: